export default {
    apiFile: "./src/store/slices/api.ts",
    schemaFile: "../api/src/openapi.yaml",
    apiImport: "apiSlice",
    exportName: "backendApi",
    argSuffix: "Req",
    responseSuffix: "Resp",
    // operationNameSuffix: "",
    hooks: true,
    // unionUndefined: false,
    tag: true,
    // encodePathParams: false,
    // encodeQueryParams: false,
    // flattenArg: false,
    // includeDefault: false,
    // mergeReadWriteOnly: false,
    // httpResolverOptions: {},
    outputFile: "./src/api/index.ts",
};
