openapi: 3.1.1

info:
  title: Winston
  description: OpenAPI specification for the Winston backend.
  contact:
    name: Mike Burgess
  license:
    name: MIT Non-AI License
    url: https://github.com/mddburgess/winston/blob/main/LICENSE.md
  version: v1

servers:
  - description: Local server used for development.
    url: http://localhost:8080

paths:
  /api/v1/channels:
    get:
      $ref: ./paths/channels/listChannels.yaml
  /api/v1/channels/{handle}:
    get:
      $ref: ./paths/channels/getChannel.yaml
  /api/v1/channels/{handle}/properties:
    patch:
      $ref: ./paths/channels/patchChannelProperties.yaml
  /api/v1/channels/{handle}/videos:
    get:
      $ref: ./paths/videos/listVideos.yaml
  /api/v1/videos/{id}:
    get:
      $ref: ./paths/videos/getVideo.yaml
  /api/v1/videos/{id}/comments:
    get:
      $ref: ./paths/comments/listComments.yaml
  /api/v1/comments/{id}/properties:
    patch:
      $ref: ./paths/comments/patchCommentProperties.yaml
  /api/v1/authors:
    get:
      $ref: ./paths/authors/listAuthors.yaml
  /api/v1/authors/{handle}:
    get:
      $ref: ./paths/authors/getAuthor.yaml
    patch:
      $ref: ./paths/authors/patchAuthor.yaml
  /api/v1/authors/{handle}/channels:
    get:
      $ref: ./paths/authors/getAuthorChannelSummary.yaml
  /api/v1/authors/{handle}/videos:
    get:
      $ref: ./paths/authors/getAuthorVideoSummary.yaml
  /api/v1/channels/{id}/thumbnail:
    get:
      $ref: ./paths/thumbnails/getChannelThumbnail.yaml
  /api/v1/videos/{id}/thumbnail:
    get:
      $ref: ./paths/thumbnails/getVideoThumbnail.yaml
  /api/v1/authors/{id}/thumbnail:
    get:
      $ref: ./paths/thumbnails/getAuthorThumbnail.yaml
  /api/v1/fetch/limits:
    get:
      $ref: ./paths/fetch/getFetchLimits.yaml
  /api/v1/notifications:
    get:
      $ref: ./paths/notifications/subscribe.yaml
  /api/v1/pull:
    post:
      $ref: ./paths/pull/pull.yaml
  /api/v1/pull/quote:
    post:
      $ref: ./paths/pull/quotePull.yaml
  /api/v1/settings:
    get:
      $ref: ./paths/settings/getSettings.yaml
    patch:
      $ref: ./paths/settings/patchSettings.yaml

tags:
  - name: Channels
    description: Endpoints to get data related to channels.
  - name: Videos
    description: Endpoints to get data related to videos.
  - name: Comments
    description: Endpoints to get data related to comments and replies.
  - name: Authors
    description: Endpoints to get data related to comment authors.
  - name: Thumbnails
    description: Endpoints to get thumbnail images.
  - name: Fetch
    description: Endpoints related to fetching data from YouTube.
  - name: Notifications
    description: Endpoints related to getting fetch events.
  - name: Pull
    description: Endpoints related to pulling data from YouTube.
  - name: Settings
    description: Endpoints to get and set application settings.
