extends:
  - ["spectral:oas", all]
  - "@apisyouwonthate/style-guide"
  - "@stoplight/spectral-documentation"
rules:
  docs-tags-alphabetical: off
  hosts-https-only-oas3: warn
  no-security-schemes-defined: warn
  no-x-headers: warn
  openapi-tags-alphabetical: off
